[book]
title = "bashprof"
authors = ["Simon Leischnig"]
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/bashmgmt/bashprof"
additional-css = ["theme.css"]
